name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git User
      run: |
        git config --global user.name "and86rey"
        git config --global user.email "125742554+and86rey@users.noreply.github.com"
    - name: Verify API Key
      run: |
        if [ -z "${{ secrets.FMP_API_KEY }}" ]; then
          echo "Error: FMP_API_KEY is not set in GitHub Secrets."
          exit 1
        fi
    - name: Verify Access Token
      run: |
        if [ -z "${{ secrets.ACCESS_TOKEN }}" ]; then
          echo "Error: ACCESS_TOKEN is not set in GitHub Secrets."
          exit 1
        fi
    - name: Replace API Key
      run: |
        echo "Before replacement:"
        grep "YOUR_FMP_API_KEY" index.html || echo "Placeholder not found"
        sed -i "s/YOUR_FMP_API_KEY/${{ secrets.FMP_API_KEY }}/g" index.html
        echo "After replacement:"
        grep "YOUR_FMP_API_KEY" index.html || echo "Placeholder replaced"
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.6.4
      with:
        branch: gh-pages
        folder: .
        token: ${{ secrets.ACCESS_TOKEN }}
        clean: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
